# Path to root of this dir.
dotfiles_path: "<%= File.expand_path(File.dirname(__FILE__)) %>"

# Specify where symlinks will go (normally user's $HOME).
symlinks_path: "<%= ENV['HOME'] %>"

# Editor
editor: mate -w

# Only files in this list will be compiled and symlinked.
symlinks:
  ackrc:     .ackrc
  nzbget:    .nzbget
  zshrc:     .zshrc
  gemrc:     .gemrc
  gitconfig: .gitconfig
  gitignore: .gitignore
  irbrc:     .irbrc
  railsrc:   .railsrc

# Personal info
nzbget:
  host: YOUR_NNTP_HOST
  user: YOUR_NNTP_USER
  pass: YOUR_NNTP_PASS
 
gitconfig:
  name: YOUR_NAME
  email: YOUR_EMAIL

github:
  user: YOUR_GITHUB_LOGIN
  token: YOUR_GITHUB_API_TOKEN