# Path to root of this dir.
dotfiles_path: "<%= File.expand_path(File.dirname(__FILE__)) %>"

# Specify where symlinks will go (normally user's $HOME).
symlinks_path: "<%= ENV['HOME'] %>"

# Only files in this list will be symlinked.
symlinks:
  zshrc:         .zshrc
  zshenv:        .zshenv
  ackrc:         .ackrc
  gemrc:         .gemrc
  gitconfig:     .gitconfig
  gitignore:     .gitignore
  irbrc:         .irbrc
  railsrc:       .railsrc
  takeup:        .takeup
  todo:          .todo
  ssh_config:    .ssh/config

zsh:
  editor: 'mate -w'
  theme: 'robbyrussell'

  plugins:
    - git
    - brew
    - bundler
    - autojump
    - cap
    - extract
    - gem
    - github
    - heroku
    - history-substring-search
    - lighthouse
    - node
    - npm
    - osx
    - thor
 
gitconfig:
  name: YOUR_NAME
  email: YOUR_EMAIL

github:
  user: YOUR_GITHUB_LOGIN
  token: YOUR_GITHUB_API_TOKEN

# Add personal gitignores here
gitignore:
  - config/initializers/YOUR_NAME_initializer.rb

# Setup ssh config for enabling `ssh foo` type of shortcuts
ssh:
  - name: 'foo'
    host: 'foo.example.com'
    user: 'foo_user'
    identity: "<%= ENV['HOME'] %>/.ec2/foo"
    alive:
      interval: 30
      count: 120