# Path to root of this dir.
dotfiles_path: "<%= File.expand_path(File.dirname(__FILE__)) %>"

# Specify where symlinks will go (normally user's $HOME).
symlinks_path: "<%= ENV['HOME'] %>"

# Only files in this list will be symlinked.
symlinks:
  ackrc:     .ackrc
  nzbget:    .nzbget
  zshrc:     .zshrc
  gemrc:     .gemrc
  gitconfig: .gitconfig
  gitignore: .gitignore
  irbrc:     .irbrc
  railsrc:   .railsrc

zsh:
  editor: mate -w
  theme: 'robbyrussell'

  paths:
    - /usr/bin
    - /bin
    - /usr/sbin
    - /sbin
    - /usr/local/bin
    - /usr/X11/bin
    - "<%= ENV['HOME'] %>"/Executables

  plugins:
    - git
    - brew
    - bundler
    - autojump
    - cap
    - extract
    - gem
    - github
    - heroku
    - history-substring-search
    - lighthouse
    - node
    - npm
    - osx
    - thor
 
gitconfig:
  name: YOUR_NAME
  email: YOUR_EMAIL

github:
  user: YOUR_GITHUB_LOGIN
  token: YOUR_GITHUB_API_TOKEN

gitignore:
  - .DS_Store
  - .svn
  - *~
  - *.scratch.*
  - *.swp